version: '3.1'

networks:
  maria_net:
    driver: bridge

services:
  db:
    image: mariadb:10.6
    restart: always
    networks:
      - maria_net
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_USER: user
      MYSQL_PASSWORD: usersenha

  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - maria_net
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1


